#pragma once

#define MASTER_LEFT 
#define SPLIT_USB_DETECT
#define TAPPING_TERM 180
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
#define ADNS5050_SCLK_PIN GP13
#define ADNS5050_SDIO_PIN GP12
#define ADNS5050_CS_PIN GP14
#define WS2812_DI_PIN GP0
#define RGBLED_NUM 2
#define RGBLIGHT_LED_MAP { 0,1 }